language: node_js
node: js:
  - '11.14'
cache:
  directories:
    - node_modules
script:
  - npm run coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on: 
    branch: master